### PR TITLE
Fixes “Uncaught TypeError” when datepicker is shown

### PR DESCRIPTION
**Pull request by pryley**
“Cannot read property 'getBoundingClientRect' of undefined”

### CODE REVIEW

**Comment by qodesmith** [comment]
Can you provide steps to reproduce the problem? Thanks.

**Comment by pryley** [comment]
### package.json
```json
{
  "private": true,
  "dependencies": {
    "js-datepicker": "^1.2.1"
  },
  "devDependencies": {
    "babel-preset-es2015": "^6.24.0",
    "gulp": "^3.9.1",
    "gulp-babel": "^6.1.2",
    "gulp-concat": "^2.6.1",
    "gulp-if": "^2.0.2",
    "gulp-uglify": "^2.0.0",
    "yamljs": "^0.2.3",
    "yargs": "^7.0.1"
  }
}
```

### gulpfile.js
```js
var args   = require('yargs').argv;
var babel  = require('gulp-babel');
var concat = require('gulp-concat');
var gulp   = require('gulp');
var gulpif = require('gulp-if');
var uglify = require('gulp-uglify');
var yaml   = require('yamljs');

var config = yaml.load('config.yml');

gulp.task('js', function() {
    return gulp.src(config.scripts['main.js'])
    .pipe(concat('main.js'))
    .pipe(babel({
        presets: [['es2015', {modules: false}]],
    }))
    .pipe(gulpif(args.production, uglify({
         preserveComments: 'license',
    })))
    .pipe(gulp.dest(config.dest.js))
});
```

### config.yml
```yml
scripts:
  main.js:
    - node_modules/js-datepicker/datepicker.js
    - src/js/main.js
dest:
  js: assets/js/
```

### main.js
```js
if( document.querySelector( '#start-date' )) {
    var startDate = datepicker( '#start-date' );
}
if( document.querySelector( '#end-date' )) {
    var endDate = datepicker( '#end-date' );
}
```

### index.html
```html
<!-- ... -->
<div class="date-picker">
    <label for="start-date">Start date</label>
    <input type="text" id="start-date" name="start-date" placeholder="Start date">	
</div>
<!-- ... -->
```

### Compile JS with gulp
```sh
$ gulp js
```

### Result
image

**Comment by qodesmith** [comment]
Thanks for a thorough example! With your code as-is, I wasn't able to reproduce. I had to style the `.date-picker` div with `position: absolute` in order to reproduce. In any case, indeed the issue was conditionally storing the calendar's parent element on the instance. If you can change your PR slightly to remove `instance.parent = parent;` from line 126 then I'll merge.

**Comment by pryley** [comment]
Done.

In my particular implementation, the `.date-picker` element has `float:left;`.

image

**Pull request merged**
