### PR TITLE
js-datepicker.d.ts

### PR DESCRIPTION
**Pull request by Puzzlefactory**
A definition file for Typescript so the library can be used in Typescript projects.

### CODE REVIEW

**Comment by qodesmith** [comment]
@Puzzlefactory Since I'm new to TS, can you point me to any documentation that explains the definition file?

**Comment by Puzzlefactory** [comment]
I will comment the code with information on each step but have been crazy busy... sorry.

I am not some Typescript guru either, the info I used I got from: https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html

Additionally used https://github.com/Microsoft/dts-gen in the past to generate some definition files. 

Basically what they are is a file that helps Typescript define the type from a JavaScript library so it can be used like this: **import datepicker from "js-datepicker**   datepicker(arg, arg);

In this case since your datepicker is beautifully simple (why we used it) there is only one entry point so only one namespace is declared: "js_datepicker" and only one function (js_datepicker) needs to be declared that has two arguments of the type <any> (which is common for JS to TS) 

Not sure the prototype on Array is defined properly but have not had a chance to mess around with it.

Usually these things are submitted for inclusion in @type but to me it seemed you liked to keep your datepicker simple and compact. Having to install a type definition from @type would seem to be less elegant than having the type declaration in the package. This way if someone wanted to use it with Typescript it would "just work" without any additional steps.

My feelings won't be hurt if you rewrite the definition and no credit is needed either. 

Thanks for the work you have done!

**Comment by nkovacic** [comment]
A typescript definition would be very useful for angular apps, which use the language heavily.

**Comment by qodesmith** [comment]
@nkovacic I'm fine with merging this PR is someone can walk me through it to understand what exactly goes into a Typscript definition. Or perhaps there's an article someone can point me to? Otherwise, I have no reference to gauge this PR against. Thanks all!

**Comment by venimus** [comment]
I don't see any reason for this file to be bundled, as this definition should reside and be defined in the project not the library

**Comment by qodesmith** [comment]
@venimus Thanks for the insight. Since I'm not familiar with Typscript (and I have no real urge or interest to dive into it), I'd be curious about your comment. Do projects typically rely on libraries that they use to already have TS definitions? Or is that the responsibility of the project as you say?

Not that I'm against adding a TS definition file, but I still have no idea what it should look like and since I don't use TS I'm relying on anyone here in the community to shed some light. I'll leave this PR open so we can continue discussion.

**Comment by nkovacic** [comment]
Bundled TypeScript definitions are much more developer friendly, because when you download the package, you dont have to also search the definition on npm.
You can see an example of a bundled TypeScript definition on my repository https://github.com/nkovacic/angular-touchspin

**Comment by venimus** [comment]
I have never seen a generic JS library to have bundled such a definition, but I never looked for it specifically. I don't use Angular so I'm not sure if it is helpful or it is a practice. 

Despite that I think the definition is wrong as it exports a different class name than the original (`js_datepicker` vs `Datepicker`). It also looks useless because defines `any` for everything.

**Comment by qodesmith** [comment]
@nkovacic Thanks for the input. Would you be able to walk me through the TS definition file in this PR? Or perhaps make a PR of your own to show how it would be done? I'm fine with merging one into this repo on the condition that I get some consensus around it being correct!

@venimus I had my reservations too about this definition file being incorrect. I actually ok with the `any` stuff cuz I have no future plans to do anything TS related so the purpose of a TS definition file with this library would simply be to alleviate some pain from developers who are importing it into projects that _do_ use TS.

**Comment by Puzzlefactory** [comment]
JavaScript is not useless with its type of “any” for all variables so not sure I understand your argument.

JavaScript variables often have a type of any in TypeScript definitions, reason being is they can contain any data type, string, int, Array, object, etc. so it is pretty usual to see the type of “any” in TypeScript definitions.

This library essentially has one entry point and no dependencies need so the type any works just fine. It is the reason I chose to use this library. 

I did not want to write a type definition for an obsolete version of react-datepicker to match an old version of React for a Sharepoint project I got pulled onto because the team could not get a datepicker to work. The problem was most were new to TupeScript. The current iterations of react-datepicker have a definition on @type. It would have been throwaway work to write a new one and a lot of effort. The need was a simple datepicker and this one fit the bill.

TypeScript allows it to be imported and the library can be used as intended. Currently it is being used on an internal application daily at my employer (a large auto manufacturer) using this very definition.

Due to the nature of this discussion I cannot state my employer because it could be seen as an endorsement but will do so privately to the owner of this library and provide proof if that is the level of comfort he needs.

Of course if he wants to test it first hand an Angular project can be set up quickly using @angular/cli and import the library using the definition.

It is no matter to me if this PR is accepted or not. If I felt strongly about it I would simply submit it to @type where they know more about such things. It seemed to me the author felt strongly that his library require no dependencies so I wanted to offer him the option.

**Comment by Puzzlefactory** [comment]
Yikes, sorry replied by email so it ended up being big block of solid text

**Comment by qodesmith** [comment]
@Puzzlefactory If you can give me a brief overview of how your TS definition file works, I'm all for merging this. You're correct that my intention was to create a library with _no_ dependencies - just good 'ol fashion JavaScript. If the TS definition file helps, I'm all for including it. I would like to see what you have to say about the comment around `js_datepicker` being the wrong name.

Anyways, to reiterate, I'm fine with merging a TS definition file into this project so long as I know it will work for those that need it. Feel free to reach out to me directly. Thank you!

**Comment by venimus** [comment]
> JavaScript is not useless with its type of “any” for all variables so not sure I understand your argument.

I meant TypeScript definition could be more specific for types, as currently it only shows the number of arguments, but not the types accepted.

I also chose this library because has no dependencies and has a repository definition and looks simple enough to do the job. Although I would like to be able to set dynamically some of the options and callbacks after getting a new instance. I need to link logically two fields and make a date range picker.

I joined the discussion to the PR only because I use the library and it has the potential to be one of the most popular but I didn't want to have too much overhead in it.

**Comment by Puzzlefactory** [comment]
That is generally the best option, adding it into the project manually is less “ideal” but gives the author more control.

I was not sure if the author preferred another way so I wanted to give him control.

Either way he would have something else to maintain. He is not a fan of TS so maybe the fourth option is best. 

Document it in the readme so those seeking an answer have one in the best place to find one and deny the PR. 

Someone may still submit something to @type but it is of no matter to him.

**Comment by qodesmith** [comment]
@Puzzlefactory Sorry this fell by the wayside. Are you sure you want to close this? I'm still for merging a TS definition file once I understand this better.

**Pull request closed without merging**
