### PR TITLE
Added year input overlay customisation options

### PR DESCRIPTION
**Pull request by dionmes**
Add two customisation options for the UI text in the year overlay. Now you can localise the UI completely from a user perspective. The labels are pretty long, but any shorter would make them ambiguous: customYearSubmitLabel & customYearInputPlaceholder.

### CODE REVIEW

**Comment by dionmes** [comment]
Now compatible with IE/Edge

**Comment by qodesmith** [comment]
@dionmes Hey, I've been meaning to take a look at this. Been super busy at the moment, but just wanted to touch base and let you know I haven't forgotten :)

**Comment by dionmes** [comment]
No worries, for me it works out nice. I have minimal JS knowledge, but this works.

**Comment by qodesmith** [comment]
@dionmes Thanks for the PR. I looked over your code changes and saw you removed a lot of the ES7 stuff. In the end, I implemented the feature you were looking for but I couldn't merge this request and I don't want to take the ES7 stuff out. Check out the new docs and you'll see that you can now customize the overlay's button text and placeholder text.

**Comment by dionmes** [comment]
Hi, Thanks for the update. 
I get that you don't want to take out the ES7 code, it is very elegant. I'll need to stick to my own version now because I need the browser support, but that is not an issue. Best regards.

**Comment by qodesmith** [comment]
@dionmes Cool. If browser support is what's needed, you can always use the minified js file. It compiles down to good 'ol fashion ES5.

**Comment by dionmes** [comment]
And see here my lack of JS knowledge 🤔 . I did not know the minified is ES5 compatible... Thank you !

**Pull request closed without merging**
